### ISSUE TITLE
RedisHealthIndicator is not exported

### ISSUE THREAD

**Issue by TrejGun** [liaoliaots/nestjs-redis#102]
it was removed in this commit

https://github.com/liaoliaots/nestjs-redis/commit/076cdc31539409146302e2d666fdcc7aa2e612e3#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567L5

it probably should be exported from here 

https://github.com/liaoliaots/nestjs-redis/commit/076cdc31539409146302e2d666fdcc7aa2e612e3#diff-2780ab9bea6364cc71f6004bbc2aed48cb3379af9f7b3d4e6377b6a7560c0757R2

but for some reason was lost

**Comment by liaoliaots** [comment]
Sorry, my bad, the document is being written.

For v3.0.0, you need import `RedisHealthModule` and `RedisHealthIndicator` via:
```TypeScript
import { RedisHealthModule, RedisHealthIndicator } from '@liaoliaots/nestjs-redis/health';
// Things to note: The RedisHealthModule is not a global module.
```
1: add `RedisHealthModule` to `imports` list of `@Module()` decorator.
2: inject `RedisHealthIndicator` provider into our service, controller, etc.

For moving health checks to the **health** folder the reason is `@nestjs/terminus` should be an optional dependency, not required. 😃😃😃

**Comment by liaoliaots** [comment]
If we expose that in /lib/index.ts, so `@nestjs/terminus` must be installed.

**Comment by TrejGun** [comment]
oh i see
thanks

**Comment by TrejGun** [comment]
the interface was better before
